### PR TITLE
Update feedstock for poliastro 0.7.0

### PR DESCRIPTION
**Pull request by Juanlu001**
@anhiga

### CODE REVIEW

**Comment by Juanlu001** [comment]
I'm getting this on AppVeyor:

```
The following packages will be SUPERSEDED by a higher-priority channel:
    conda:            4.3.25-py35_0 defaults    --> 4.3.23-py35_0 conda-forge
    conda-env:        2.6.0-0       defaults    --> 2.6.0-0       conda-forge
ERROR conda.core.link:_execute_actions(337): An error occurred while installing package 'conda-forge::anaconda-client-1.6.5-py_0'.
CondaError: Cannot link a source that does not exist. C:\Miniconda35-x64\Scripts\conda.exe
Attempting to roll back.
CondaError: Cannot link a source that does not exist. C:\Miniconda35-x64\Scripts\conda.exe
Command exited with code 1
```

any idea @jakirkham @ocefpaf?

**Comment by jakirkham** [comment]
Please [re-render]( https://github.com/conda-forge/conda-smithy#re-rendering-an-existing-feedstock ) with the latest `conda-smithy` (2.4.0).

**Comment by Juanlu001** [comment]
BTW @jakirkham last re-render with conda-smithy broke the badges:

https://github.com/conda-forge/poliastro-feedstock/commit/a28d176adfe#diff-04c6e90faac2675aa89e2176d2eec7d8

but I don't see anything wrong in the template:

https://github.com/conda-forge/conda-smithy/blob/v2.4.0/conda_smithy/templates/README.md.tmpl

Any ideas?

**Comment by jakirkham** [comment]
It uses the directory name on your computer to fill out those badges.

**Comment by Juanlu001** [comment]
Thanks for the quick response, will change that then.

**Pull request merged**
