### PR TITLE
Remove Python pinning

### PR DESCRIPTION
**Pull request by Juanlu001**

### CODE REVIEW

**Comment by isuruf** [comment]
You need to rerender after adding `noarch: python`

**Comment by Juanlu001** [comment]
Oops, thanks. How can I do that?

**Comment by Juanlu001** [comment]
https://github.com/conda-forge/spiceypy-feedstock#about-conda-forge

`conda smithy rerender`

**Comment by Juanlu001** [comment]
Done, thanks @isuruf

**Pull request merged**
